const movies = [
    "Lord of the Rings: Return of the King",
    "Chimes at Midnight",
    "Lady Bird",
    "We Were Here",
    "The Gunfighter",
    "Apocalypse Now",
    "Ace Ventura: Pet Detective",
    "The Apartment",
    "Meet Me in St. Louis",
    "Schindler's List",
    "Sideways",
    "Inside Out",
    "Shadow of a Doubt",
    "Amazing Grace",
    "The Wild Child",
    "Grave of the Fireflies",
    "Catch Me If You Can",
    "Gangs of New York",
    "The Prestige",
    "Interstellar",
    "The Irishman",
    "Mr. Turner",
    "The Manchurian Candidate",
    "Pulp Fiction",
    "Taxi Driver",
    "The Searchers",
    "The Man Who Shot Liberty Valance",
    "Dunkirk",
    "Amour",
    "Before Midnight",
    "Carol",
    "WALL-E",
    "A Separation",
    "Zero Dark Thirty",
    "Anatomy of a Murder",
    "The Hurt Locker",
    "Snow White and the Seven Dwarfs",
    "Collective",
    "Double Indemnity",
    "Woodstock",
    "I Am Not Your Negro",
    "Portrait of a Lady on Fire",
    "My Fair Lady",
    "The Social Network",
    "The Bride of Frankenstein",
    "Toy Story",
    "Small Axe: Lovers Rock",
    "Beauty and the Beast",
    "Spirited Away",
    "Big Daddy",
    "Dune",
    "Fantasia",
    "Gravity",
    "The Lady Eve",
    "Mean Streets",
    "Children of Paradise",
    "The Grapes of Wrath",
    "Don't Look Now",
    "Rocks",
    "Parasite",
    "Ratatouille",
    "Nashville",
    "Killer of Sheep",
    "12 Years a Slave",
    "The Maltese Falcon",
    "Rosemary's Baby",
    "Manchester by the Sea",
    "12 Angry Men",
    "The Shop Around the Corner",
    "Dumbo",
    "American Graffiti",
    "A Streetcar Named Desire",
    "Battleship Potemkin",
    "Psycho",
    "4 Months, 3 Weeks and 2 Days",
    "Gone with the Wind",
    "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
    "The Third Man",
    "My Left Foot",
    "The Wild Bunch",
    "Jules and Jim",
    "All About Eve",
    "Rashomon",
    "Hoop Dreams",
    "North by Northwest",
    "Some Like It Hot",
    "Pan's Labyrinth",
    "The Treasure of the Sierra Madre",
    "The Lady Vanishes",
    "Touch of Evil",
    "Pinocchio",
    "Moonlight",
    "City Lights",
    "Singin' in the Rain",
    "Notorious",
    "Vertigo",
    "Three Colors: Red",
    "Boyhood",
    "Casablanca",
    "Rear Window",
    "The Godfather",
    "Citizen Kane"
]